#!/usr/bin/env bash

# This script is used to setup the environment for the first time

echo -e "Setting up the environment...\n"
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get -y remove vim.tiny vim

echo -e "Installing the required dependencies...\n"
# Mandatory dependencies
sudo apt-get install -y software-properties-common build-essential
sudo apt -y install gdb lcov libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libssl-dev lzma lzma-dev tk-dev uuid-dev zlib1g-dev gcc make pkg-config

# Adding the required repositories
echo -e "Adding the required repositories...\n"
sudo add-apt-repository ppa:deadsnakes/ppa -y # For Python
sudo add-apt-repository -y ppa:jonathonf/vim     # For Vim
sudo apt-add-repository -y ppa:rael-gc/rvm    # For Ruby
sudo apt update ; sudo apt-get upgrade -y

# Installing some plugins
echo -e "Adding Plugins...\n"
# Vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Installing SQL Databases
echo -e "Installing Databases...\n"
# MySQL
sudo apt install -y mysql-server

# PostgreSQL
sudo apt install -y postgresql postgresql-contrib

# For Nvim
wget https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
sudo mv nvim-linux64.tar.gz /usr/local/bin
cd /usr/local/bin
sudo tar xzvf nvim-linux64.tar.gz
sudo rm -fr nvim-linux64.tar.gz

# Create a symlink for nvim
sudo ln -s ./nvim-linux64/bin/nvim ./nvim
cd

# Installing LazyVim
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
