#!/usr/bin/env bash

# Last script to be ran after the environment has been configured

# Install rvm
rvm install ruby 3.3.0
gem install colorls

# Go extras
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
cd go/bin/
sudo mv subfinder /usr/bin
cd

# ZSH Plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
